"""Deterministic compute layer (Law 1). Pure Python, no LLM, no network. 100% test coverage required."""

from firm.core.compute.divergence import (
    cochange_divergence,
    divergence_flag,
    pct_change,
    realized_correlation,
)
from firm.core.compute.models import (
    BusinessModel,
    Playbook,
    StatementShape,
    build_playbook,
    detect_models,
)
from firm.core.compute.multibagger import (
    FeasibilityResult,
    GateVerdict,
    eps_growth,
    feasibility_gate,
    reinvestment_rate_from_financials,
    required_earnings_cagr,
    required_reinvestment_rate,
    serial_diluter_flag,
    sustainable_growth,
)
from firm.core.compute.quality import (
    BeneishYear,
    Flag,
    ForensicMetrics,
    ForensicScreenResult,
    ForensicThresholds,
    ForensicVerdict,
    SectorClass,
    Severity,
    accrual_ratio,
    adjusted_ebitda_bridge_gap,
    ageing_cwip_flag,
    beneish_m_score,
    capitalised_cost_share,
    cash_debt_paradox,
    cash_interest_consistency,
    cfo_pat_ratio,
    contract_asset_divergence,
    cumulative_cfo_pat_ratio,
    disclosure_completeness,
    forensic_screen,
    gain_on_sale_reliance,
    gnpa_drift_flag,
    guarantees_to_net_worth,
    held_for_sale_reserve_flag,
    other_income_share,
    promoter_loan_share,
    provision_book_divergence,
    provision_coverage_flag,
    provision_rate,
    reserve_suppression_flag,
    restructured_book_flag,
    revenue_inflation_tell,
    stock_flow_divergence,
)

__all__ = [
    # quality
    "BeneishYear",
    # business-model detection + playbooks
    "BusinessModel",
    # multibagger
    "FeasibilityResult",
    "Flag",
    "ForensicMetrics",
    "ForensicScreenResult",
    "ForensicThresholds",
    "ForensicVerdict",
    "GateVerdict",
    "Playbook",
    "SectorClass",
    "Severity",
    "StatementShape",
    "accrual_ratio",
    "adjusted_ebitda_bridge_gap",
    "ageing_cwip_flag",
    "beneish_m_score",
    "build_playbook",
    "capitalised_cost_share",
    "cash_debt_paradox",
    "cash_interest_consistency",
    "cfo_pat_ratio",
    # divergence
    "cochange_divergence",
    "contract_asset_divergence",
    "cumulative_cfo_pat_ratio",
    "detect_models",
    "disclosure_completeness",
    "divergence_flag",
    "eps_growth",
    "feasibility_gate",
    "forensic_screen",
    "gain_on_sale_reliance",
    "gnpa_drift_flag",
    "guarantees_to_net_worth",
    "held_for_sale_reserve_flag",
    "other_income_share",
    "pct_change",
    "promoter_loan_share",
    "provision_book_divergence",
    "provision_coverage_flag",
    "provision_rate",
    "realized_correlation",
    "reinvestment_rate_from_financials",
    "required_earnings_cagr",
    "required_reinvestment_rate",
    "reserve_suppression_flag",
    "restructured_book_flag",
    "revenue_inflation_tell",
    "serial_diluter_flag",
    "stock_flow_divergence",
    "sustainable_growth",
]
